version: "3.3"
services:
  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "5000:5000"
  # frontend:
  #   container_name: frontend
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./frontend
  #   ports:
  #     - "8049:8049"
